# -*- coding: utf-8 -*-
"""Movies.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OIVet16HoZ0uIJ1ZMihHRvK99tKExG58
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

df=pd.read_csv('movies_metadata.csv')

df



df.columns

df.info()

df.isnull().sum()

df = df.drop_duplicates().reset_index(drop=True)

df.duplicated().sum()

df.shape

df = df[['title','overview','genres','tagline','vote_average','popularity']]

df.head()

df['overview'] = df['overview'].fillna('')

df.iloc[0]['genres']
import ast

df['genres'] = df['genres'].apply(lambda x:" ".join ([i['name'] for i in ast.literal_eval(x)]))

df['tagline'] = df['tagline'].fillna('')

df['tagline'].count()

df['tags'] = df['overview'] + df['genres'] + df['tagline']

df.head()

df['tags'][0]

import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

nltk.download('stopwords')
nltk.download('wordnet')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
  text = re.sub(r'[^a-zA-Z]', ' ', text)
  text = text.lower()
  words = text.split()
  words = [word for word in words if word not in stop_words]
  words = [lemmatizer.lemmatize(word) for word in words]
  return ' '.join(words)

df['tags'] = df['tags'].apply(preprocess_text)

df['tags']

df = df.reset_index(drop = True)

indices = pd.Series(df.index, index=df['title']).drop_duplicates()

indices

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features = 50000,ngram_range=(1,2),stop_words='english')

tfidf_matrix = tfidf.fit_transform(df['tags'])

tfidf_matrix.shape

from sklearn.metrics.pairwise import cosine_similarity

def recommend(title, n =10):
  if title not in indices:
    return ['movie not found']

  idx = indices[title]
  sim_score = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
  similar_idx = sim_score.argsort()[::-1][1:n+1]
  return df['title'].iloc[similar_idx]

recommend('Toy Story')

import pickle

pickle.dump(tfidf_matrix, open('tfidf_matrix.pkl', 'wb'))
pickle.dump(df, open('df.pkl', 'wb'))
pickle.dump(indices, open('indices.pkl', 'wb'))
df.to_pickle('df.pkl')
pickle.dump(tfidf,open('tfidf.pkl','wb'))

